### ISSUE TITLE
没有lkl目录怎么搞

### ISSUE THREAD

**Issue by xxliao** [nivrrex/lkl-bbr#1]
大佬，我分别下载了linux 4.14和5.10和6.1的内核，打好了补丁，没有你第一步 ./arch/lkl的目录呀，请问这个目录是怎么来的，我还缺了什么步骤？

**Comment by nivrrex** [comment]
仔细看说明
要从https://github.com/lkl/linux 或者 https://github.com/ngi-mptcp/lkl-next/ 下载源文件
这些是针对原内核进行修改的，只有从这个源码才可以编译出 lkl 的内容

官方内核是没有 lkl 目录的，也不能按说明进行 lkl-bbr 的编译
而且最新的 lkl 5.18 版本编译后，使用时会出错

我修改了说明文件，可以直接从链接下载对应版本的 5.4 或者 5.10 版本的 lkl 修改版内核

**Comment by xxliao** [comment]
直接下载你编译的文件使用了，我看你是 debian10 和 debian11编译的，能直接在 Centos7 系统上面用吗？ 另外我看新版支持 BBR和BBRPLUS，FQ和FQPIE等，这些能够在配置文件里面设置吗？
最主要是，我感觉在我的OVZ小鸡上效果好象不太好

**Comment by nivrrex** [comment]
应该可以在Centos7上使用，但是没有环境，测试不了
你可以自己在配置文件里修改，如果运行后，执行ping 10.0.0.2不通，说明有问题，改回原配置即可
因为OVZ小鸡环境、是否超售、网络情况等都不一样，无法保证最终效果，不过会比没有BBRPlus要好一些

**Comment by xxliao** [comment]
等下次重装验证测试一下，3Q



--------------------------------
赣州市赣县中等专业学校

现代应用技术系 - 廖星星

联系方式：18665695790

________________________________
发件人: nivrrex ***@***.***>
发送时间: 2023年4月5日 22:29
收件人: nivrrex/lkl-bbr ***@***.***>
抄送: xxliao ***@***.***>; Author ***@***.***>
主题: Re: [nivrrex/lkl-bbr] 没有lkl目录怎么搞 (Issue #1)


应该可以在Centos7上使用，但是没有环境，测试不了
你可以自己在配置文件里修改，如果运行后，执行ping 10.0.0.2不通，说明有问题，改回原配置即可
因为OVZ小鸡环境、是否超售、网络情况等都不一样，无法保证最终效果，不过会比没有BBRPlus要好一些

―
